version: '3.2'

services:
  db:
    image: mysql:latest
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: checkline

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db

  checkline-backend:
    restart: always
    depends_on:
      - db
    image: ghcr.io/jonbeckas/checkline-backend:latest
    ports: 
      - "8081:8081"
    volumes:
      - ./backend-config.json:/usr/build/config.json

  checkline-frontend:
    image: ghcr.io/jonbeckas/checkline-frontend:latest
    ports: 
      - "8082:80"
    volumes:
      - ./frontend-config.json:/usr/share/nginx/html/assets/config/config-prod.json
